import React from 'react';
import { useApp } from '../../context/AppContext';
import { SUPER_USER } from '../../constants';
import { N } from '../../utils/helpers';

export default function Acct(){
  const ctx=useApp();const ae=ctx.cashBook||[];const inc=ae.filter(e=>e.entry_type==="Income"&&!e.reversed);const exp=ae.filter(e=>e.entry_type==="Expense"&&!e.reversal_of);const ti=inc.reduce((s,e)=>s+e.amount,0);const te=exp.reduce((s,e)=>s+e.amount,0);const ns=ti-te;const pt=inc.filter(e=>e.is_prior_term).reduce((s,e)=>s+e.amount,0);const ci={};inc.forEach(e=>{ci[e.category]=(ci[e.category]||0)+e.amount});const sAi=ae.filter(e=>e.section==="A"&&e.entry_type==="Income"&&!e.reversed).reduce((s,e)=>s+e.amount,0);const sAe=ae.filter(e=>e.section==="A"&&e.entry_type==="Expense"&&!e.reversal_of).reduce((s,e)=>s+e.amount,0);const sBi=ae.filter(e=>e.section==="B"&&e.entry_type==="Income"&&!e.reversed).reduce((s,e)=>s+e.amount,0);const sBe=ae.filter(e=>e.section==="B"&&e.entry_type==="Expense"&&!e.reversal_of).reduce((s,e)=>s+e.amount,0);const payroll=(ctx.salaries||[]).reduce((s,x)=>s+(x.netPay||0),0);const dtotal=(ctx.directPay||[]).reduce((s,x)=>s+(x.amount||0),0);const lt=(ctx.lessonWeeks||[]).reduce((s,w)=>s+w.grandTotal,0);const ltch=(ctx.lessonWeeks||[]).reduce((s,w)=>s+w.totalTeacherPay,0);const lpr=(ctx.lessonWeeks||[]).reduce((s,w)=>s+w.proprietorShare,0);const revs=ae.filter(e=>e.reversal_of).length;const lgT=ae.filter(e=>e.amount>500000).length;
  
  return(
  <div className="fu">
    <h2 style={{fontFamily:"var(--ff-d)",fontSize:"1.15rem",color:"var(--navy)",marginBottom:14}}>Financial Accounting</h2>
    <div className="card" style={{background:"linear-gradient(135deg,var(--navy) 0%,var(--navy3) 100%)",border:"none"}}>
      <div style={{color:"var(--gold2)",fontSize:".75rem",fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginBottom:12}}>P&L Summary — {ctx.termCfg?.term} {ctx.termCfg?.year}</div>
      <div className="kg">{[["Total Income",ti,"var(--gold)"],["Total Expenses",te,"var(--redbg)"],["Net Surplus",ns,ns>=0?"#86efac":"var(--redbg)"],["Payroll",payroll,"var(--slate3)"]].map(([l,v,c])=><div key={l} style={{background:"rgba(255,255,255,.06)",borderRadius:8,padding:"14px 16px"}}><div style={{fontSize:".64rem",fontWeight:700,textTransform:"uppercase",color:"rgba(255,255,255,.5)"}}>{l}</div><div style={{fontFamily:"var(--ff-m)",fontSize:"1.2rem",fontWeight:800,color:c,marginTop:5}}>{N(v)}</div></div>)}</div>
    </div>
    <div className="card"><div className="sect">Revenue by Category</div><div className="tw"><table><thead><tr><th>Category</th><th className="r">Amount</th><th className="r">%</th></tr></thead><tbody>{Object.entries(ci).sort((a,b)=>b[1]-a[1]).map(([c,a])=><tr key={c}><td style={{fontWeight:500}}>{c}</td><td className="my">{N(a)}</td><td style={{fontFamily:"var(--ff-m)",textAlign:"right",color:"var(--muted)"}}>{ti>0?(a/ti*100).toFixed(1)+"%":"0%"}</td></tr>)}<tr style={{fontWeight:700,background:"var(--navy)",color:"#fff"}}><td style={{color:"#fff"}}>TOTAL</td><td style={{fontFamily:"var(--ff-m)",textAlign:"right",color:"var(--gold2)",fontWeight:700}}>{N(ti)}</td><td style={{color:"var(--gold3)",textAlign:"right",fontFamily:"var(--ff-m)"}}>100%</td></tr></tbody></table></div></div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:14}}>
      {[["A",sAi,sAe],["B",sBi,sBe]].map(([s,i2,e2])=><div key={s} className="card"><div className="sect">Section {s}</div><div style={{fontFamily:"var(--ff-m)",fontSize:".85rem"}}><div style={{padding:"6px 0",borderBottom:"1px solid var(--border2)",display:"flex",justifyContent:"space-between"}}><span>Income</span><strong style={{color:"var(--green)"}}>{N(i2)}</strong></div><div style={{padding:"6px 0",borderBottom:"1px solid var(--border2)",display:"flex",justifyContent:"space-between"}}><span>Expense</span><strong style={{color:"var(--red)"}}>{N(e2)}</strong></div><div style={{padding:"6px 0",display:"flex",justifyContent:"space-between",fontWeight:700}}><span>Net</span><strong style={{color:i2-e2>=0?"var(--green)":"var(--red)"}}>{N(i2-e2)}</strong></div></div></div>)}
    </div>
    <div className="card"><div className="sect">Lesson Income (Separate Ledger)</div><div className="kg"><div className="kpi" style={{"--accent":"var(--navy)"}}><div className="kl">Total Lesson Revenue</div><div className="kv">{N(lt)}</div></div><div className="kpi" style={{"--accent":"var(--green)"}}><div className="kl">Teachers Paid</div><div className="kv">{N(ltch)}</div></div><div className="kpi" style={{"--accent":"var(--blue)"}}><div className="kl">Proprietor</div><div className="kv">{N(lpr)}</div></div></div></div>
    <div className="card"><div className="sect">Special Items</div><div className="tw"><table><thead><tr><th>Item</th><th className="r">Value</th></tr></thead><tbody><tr><td>Direct to Proprietor</td><td className="my">{N(dtotal)}</td></tr><tr><td>Scholarship/Mercy Students</td><td style={{fontFamily:"var(--ff-m)",textAlign:"right"}}>{(ctx.scholarships||[]).length}</td></tr><tr><td>Prior Term Recovery</td><td className="my">{N(pt)}</td></tr><tr><td>Current Term Revenue</td><td className="my">{N(ti-pt)}</td></tr></tbody></table></div></div>
    <div className="card" style={{borderTop:"3px solid var(--red)"}}><div className="sect">🛡 Audit Integrity</div><div className="tw"><table><thead><tr><th>Check</th><th>Status</th><th>Detail</th></tr></thead><tbody><tr><td>Reversal Count</td><td>{revs>5?<span className="badge bdr">HIGH ({revs})</span>:<span className="badge bdg">OK ({revs})</span>}</td><td style={{color:"var(--muted)",fontSize:".76rem"}}>Review if excessive</td></tr><tr><td>Large Transactions (&gt;₦500k)</td><td>{lgT>0?<span className="badge bdo">{lgT} flagged</span>:<span className="badge bdg">None</span>}</td><td style={{color:"var(--muted)",fontSize:".76rem"}}>Requires verification</td></tr><tr><td>AI Alerts (Unread)</td><td><span className="badge bdb">{(ctx.notifs||[]).filter(n=>!n.read).length}</span></td><td style={{color:"var(--muted)",fontSize:".76rem"}}>Click 🔔 to review</td></tr></tbody></table></div></div>
    <div className="card" style={{borderTop:"3px solid var(--navy)"}}><div className="sect">🛡 Audit Trail</div><div className="tw" style={{maxHeight:280,overflowY:"auto"}}><table><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Details</th></tr></thead><tbody>{(ctx.auditLog||[]).filter(a=>a.user!==SUPER_USER&&a.user!=="superadmin").slice(0,60).map(a=><tr key={a.aid}><td className="mn">{new Date(a.time).toLocaleString()}</td><td><span className="badge bdn">{a.user}</span></td><td style={{fontWeight:600}}>{a.action}</td><td style={{maxWidth:200,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",color:"var(--muted)",fontSize:".76rem"}}>{a.details}</td></tr>)}</tbody></table></div></div>
  </div>
  );
}
